config/routes.rb
Rails.application.routes.draw do
 
 
  devise_for :people, controllers: {sessions: "sessions",registrations: 'registrations'}



	

  	root 'welcome#index'


       #get'clientes#show'
  		resources :clientes
  		resources :articles
  		resources :demandas
  		resources :creditos
  		resources :mensualidades
  		resources :abonocreditos
  	



  
end

app/models/abonocredito.rb
class Abonocredito < ApplicationRecord
	belongs_to :mensualuidad, :foreign_key => 'mensualidad_clave'
	self.table_name = "abono_credito"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	validates :title, presence: true
	validates :body, presence: true
end

app/models/cliente.rb
class Cliente < ApplicationRecord
	self.table_name = "cliente"
	has_many :demandas

end

app/models/credito.rb
class Credito < ApplicationRecord
	self.primary_key = 'clave_credito'
	belongs_to :demanda
	has_many :mensualidad, 
    :foreign_key => 'credito_clave'
	self.table_name = "credito"

end

app/models/demanda.rb
class Demanda < ApplicationRecord
self.table_name = "demanda"
belongs_to :cliente
has_one :credito

end

app/models/mensualidad.rb
class Mensualidad < ApplicationRecord
	self.primary_key = 'clave_mensualidad'
	self.table_name = "mensualidad"
	belongs_to :credito
	has_many :abonocredito, :foreign_key => 'mensualidad_clave'
	

end

app/models/person.rb
class Person < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  validates :curp, format: { with: /\A[A-Z][AEIOUX][A-Z]{2}[0-9]{2}[0-1][0-9][0-3][0-9][MH][A-Z][BCDFGHJKLMNÑPQRSTVWXYZ]{4}[0-9A-Z][0-9]\z/i, message: 'no es un formato de CURP válido' }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/programa.rb
class Programa < ApplicationRecord
	self.table_name = "programa"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	validates :nombre, presence: true
	validates :password, presence: true
end

app/controllers/articles_controller.rb
		class ArticlesController < ApplicationController
			def index
				articles = Article.order('created_at DESC');
				render json: {status: 'SUCCESS', message:'Loadede articles', data:articles},status: :ok
			end

			
			def destroy
				articles = Article.find(params[:id])
				articles.destroy
				render json: {status: 'SUCCESS', message:'delated articles', data:articles},status: :ok
			end

		end

app/controllers/clientes_controller.rb
		class ClientesController < ApplicationController
			 before_action :authenticate_person!
			
			def index
			@cliente = Cliente.find_by_curp(current_person.curp)
				#order('fecha_nac DESC');
				#render json: {status: 'SUCCESS', message:'Loadede clientes', data:clientes},status: :ok
			end

			def show
				
				@cliente = Cliente.find(params[:id])
			end

		
		end

app/controllers/creditos_controller.rb
class CreditosController < ApplicationController
			
  
			def index
				if current_person
				creditos= Credito.order('created_at DESC');
				render json: {status: 'SUCCESS', message:'Creditos cargados!', data:creditos},status: :ok
				else

					redirect_to root_path, :notice => 'Logeate para Continuar!'
				
				end
			end

				


			def show
				if current_person

					@cliente = Cliente.find_by_curp(current_person.curp)  
					@demandas = Demanda.where(:cliente_id => @cliente.id_cliente)
					@demanda = Demanda.find(params[:id])
				else

					redirect_to root_path, :notice => 'Logeate para Continuar!'
				
				end

			end

end

			

		
	

app/controllers/demandas_controller.rb
		class DemandasController < ApplicationController
			 before_action :authenticate_person!
			
			def index
				demandas= Demanda.order('created_at DESC');
				render json: {status: 'SUCCESS', message:'Loadede demandas', data:demandas},status: :ok
			end

			def show
				@cliente = Cliente.find_by_curp(current_person.curp)
				#@demanda = Demanda.find_by_cliente_id(current_person.id)
			end

		
		end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
	layout 'member'


def after_sign_up_path_for(resource)
     welcome_index_path
  end
end

app/controllers/users_controller.rb
		class UsersController < ApplicationController
			def index
				users= User.order('created_at DESC');
				render json: {status: 'SUCCESS', message:'Loadede users', data:users},status: :ok
			end

			def show	
				users = User.find(params[:id])
				render json: {status: 'SUCCESS', message:'Loadede users', data:users},status: :ok
			end

			def destroy
				users = User.find(params[:id])
				users.destroy
				render json: {status: 'SUCCESS', message:'delated user', data:users},status: :ok
			end

		end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  	if current_person.nil?
      render layout: "member"
    else
    @cliente = Cliente.find_by_curp(current_person.curp)  
    end



  end

 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/clientes/index.html.erb
 <h1>CLIENTES</h1>
 <table style="width:100%">
  <tr>
    <th align="left">Nombre</th>
    <th align="left">CURP</th>
    <th align="left">FECHA NACIMIENTO</th>
  </tr>

  <tr>
    <td align="left"><%=@cliente.nombre%></td>
    <td align="left"><%=@cliente.curp%></td>
    <td align="left"><%=@cliente.fecha_nac%></td>
    <td><%=link_to "Mostrar", @cliente%></td>
     <td><%=link_to "Demandas", demanda_url(@cliente)%></td>
  </tr>

</table> 

<%=link_to "Volver", root_path%>

app/views/clientes/show.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

<div>
	<p><%=@cliente.nombre%></p>

	<p><%=@cliente.curp%></p>

</div>


</body>
</html>

app/views/creditos/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <%@demandas.each do |demanda| %>
    <%if demanda.id_demanda == @demanda.id_demanda%>

    <header> 
      <h1 align="center">Hola <%=@cliente.nombre.downcase%> Estos son tus creditos</h1>
    </header>

    <div align="center" > 
    <div style=" width: 80%;"  type="button" class="btn btn-info" data-toggle="collapse" data-target="#demo">Clave: <%=demanda.credito.clave_credito%></div>
      <div id="demo" class="collapse">
      <table class="table table-bordered" style="background-color:#fff; width: 80%;">
         <thead style="background-color: #EEE;">
          <tr>
              <th align="left">Clave Credito</th>
              <th align="left">Valor Solucion</th>
              <th align="left">Costo Contado</th>
              <th align="left">Costo Financiamiento</th>
              <th align="left">Pago Mensual</th>
              <th align="center">Mensualidades</th>            
          </tr>
         </thead>

          <tr>
              <td align="left"><%=demanda.credito.clave_credito%></td>
              <td align="left"><%=demanda.credito.valor_solucion%></td>
              <td align="left"><%=demanda.credito.costo_contado%></td>
              <td align="left"><%=demanda.credito.costo_financiamiento%></td>
              <td align="left"><%=demanda.credito.pago_mensual%></td>
              <td align="center">
              <%= link_to '<button type="button" class="button-slim">Ir</button>'.
                  html_safe,mensualidade_url(@demanda.credito.clave_credito) %>
              </td>
          </tr>
        </table> 
    </div>
    </div> 

        <% end %>
      <% end %>
  </body>
</html>

app/views/demandas/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
<header >
    <h1 align="center">Hola  <%=@cliente.nombre.downcase%> estas son tu demandas</h1>
</header>
    


    <% @ban=@cliente.demandas.empty?%>


    <%@cliente.demandas.any? do%> 

<div class="row" style="margin:50px;"  id="div-alert-detventa">



      <table class="table table-bordered" style="background-color:#fff;">
        <thead style=" background-color: #EEE;">
          <th >MODULO</th>
          <th>TIPO CLIENTE</th>
          <th>ENGANCHE</th>
          <th>ESTADO</th>
          <th>CREDITO</th>
        </thead>

         <% @cliente.demandas.each do |demanda| %>
          <tr>
              <td align="left"><%=demanda.modulo%></td>
              <td align="left"><%=demanda.tipo_cliente%></td>
              <td align="left"><%=demanda.enganche%></td>
              <td align="left"><%=demanda.estatus%></td>
              <td align="left">
                <%= link_to '<button type="button" class="button-slim">Ir</button>'.
                html_safe,credito_url(demanda.id_demanda) %>
             </td>
           
           
              
         
       
    <%end%>


        <tbody>
         
        </tbody>
      </table>  
    </div>





    <%end%>



    <%if @ban == true %> 
    <p>No hay demandas pendientes</p>
    <%end%>
    <br>
    <%=link_to "Volver", root_path%>



</body>
</html>

app/views/welcome/_formulario_inicio.html.erb
<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="field">
    <%= f.label :email,"Correo"%><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :password,"Contraseña" %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <% if devise_mapping.rememberable? -%>
    <div class="field">
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me %>
    </div>
  <% end -%>

  <div class="actions">
    <%= f.submit "Iniciar" %>
  </div>
<% end %>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Bienvenido</title>
</head>

  <body >
    <% if person_signed_in? %>

    	<header >
        <h2 align="center"  >
            Bienvenido <%=@cliente.nombre.downcase %> al modulo para clientes Insuvi
          </h2>
        
      </header>
    	<div align="center"  style="margin: 50px; " >

          
          <br>
          <br>
          <h1>
                <%= link_to '<button type="button" class="button">Demandas</button>'.
                html_safe,demanda_url(@cliente.id) %>
               
          </h1>
           <h1>
                <%= link_to '<button type="button" class="button">Creditos</button>'.
                html_safe,demanda_url(@cliente.id) %>
               
          </h1>

      </div>
     


    <% else %>
    
<header >
  <h1 >Bienvenido a la pagina de inicio</h1>
</header>
    

     <div align="center" class="center-div" >
      <br>
      
      <p>Registrate:</p>
     
      	
         <%= link_to '<button type="button" class="button">Sign In</button>'.html_safe, new_person_registration_path %> 

      
      
      <br>
      <br>

      <p>Iniciar Sesion:</p>

      <%= link_to '<button type="button" class="button">Login</button>'.html_safe, new_person_session_path %> 
      
      </div>
      

    <% end -%>

  </body>
</html>

app/views/welcome/logeo.html.erb
<h1>Hola favor de logear con tu usuario</h1>