config/routes.rb
Rails.application.routes.draw do
 
 
  devise_for :people, controllers: {sessions: "sessions",registrations: 'registrations'}



	

  	root 'welcome#index'


       #get'clientes#show'
  		resources :clientes
  		resources :articles
  		resources :demandas
  		resources :creditos
  		resources :mensualidades
  		resources :abonocreditos
  	



  
end

app/models/abonocredito.rb
class Abonocredito < ApplicationRecord
	belongs_to :mensualuidad, :foreign_key => 'mensualidad_clave'
	self.table_name = "abono_credito"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	validates :title, presence: true
	validates :body, presence: true
end

app/models/cliente.rb
class Cliente < ApplicationRecord
	self.table_name = "cliente"
	has_many :demandas

end

app/models/credito.rb
class Credito < ApplicationRecord
	self.primary_key = 'clave_credito'
	belongs_to :demanda
	has_many :mensualidad, 
    :foreign_key => 'credito_clave'
	self.table_name = "credito"

end

app/models/demanda.rb
class Demanda < ApplicationRecord
self.table_name = "demanda"
belongs_to :cliente
has_one :credito

end

app/models/mensualidad.rb
class Mensualidad < ApplicationRecord
	self.primary_key = 'clave_mensualidad'
	self.table_name = "mensualidad"
	belongs_to :credito
	has_many :abonocredito, :foreign_key => 'mensualidad_clave'
	

end

app/models/person.rb
class Person < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  validates :curp, format: { with: /\A[A-Z][AEIOUX][A-Z]{2}[0-9]{2}[0-1][0-9][0-3][0-9][MH][A-Z][BCDFGHJKLMNÑPQRSTVWXYZ]{4}[0-9A-Z][0-9]\z/i, message: 'no es un formato de CURP válido' }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/programa.rb
class Programa < ApplicationRecord
	self.table_name = "programa"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	validates :nombre, presence: true
	validates :password, presence: true
end

app/controllers/articles_controller.rb
		class ArticlesController < ApplicationController
			def index
				articles = Article.order('created_at DESC');
				render json: {status: 'SUCCESS', message:'Loadede articles', data:articles},status: :ok
			end

			
			def destroy
				articles = Article.find(params[:id])
				articles.destroy
				render json: {status: 'SUCCESS', message:'delated articles', data:articles},status: :ok
			end

		end

app/controllers/clientes_controller.rb
		class ClientesController < ApplicationController
			 before_action :authenticate_person!
			
			def index
			@cliente = Cliente.find_by_curp(current_person.curp)
				#order('fecha_nac DESC');
				#render json: {status: 'SUCCESS', message:'Loadede clientes', data:clientes},status: :ok
			end

			def show
				
				@cliente = Cliente.find(params[:id])
			end

		
		end

app/controllers/creditos_controller.rb
class CreditosController < ApplicationController
			
  
			def index
				if current_person
				creditos= Credito.order('created_at DESC');
				render json: {status: 'SUCCESS', message:'Creditos cargados!', data:creditos},status: :ok
				else

					redirect_to root_path, :notice => 'Logeate para Continuar!'
				
				end
			end

				


			def show
				if current_person

					@cliente = Cliente.find_by_curp(current_person.curp)  
					@demandas = Demanda.where(:cliente_id => @cliente.id_cliente)
					@demanda = Demanda.find(params[:id])
				else

					redirect_to root_path, :notice => 'Logeate para Continuar!'
				
				end

			end

end

			

		
	

app/controllers/users_controller.rb
		class UsersController < ApplicationController
			def index
				users= User.order('created_at DESC');
				render json: {status: 'SUCCESS', message:'Loadede users', data:users},status: :ok
			end

			def show	
				users = User.find(params[:id])
				render json: {status: 'SUCCESS', message:'Loadede users', data:users},status: :ok
			end

			def destroy
				users = User.find(params[:id])
				users.destroy
				render json: {status: 'SUCCESS', message:'delated user', data:users},status: :ok
			end

		end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  	if current_person.nil?
      render layout: "member"
    else
    @cliente = Cliente.find_by_curp(current_person.curp)  
    end



  end

 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Insuvi</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    
      
        <% if alert %>
        <p class="alert alert-danger"><%= alert %></p> 
        <% end %>

      <div>
         
          <div class="flex-container">
              <div class="flex-container" >
               <a class="navbar-link">Programas</a> 
              </div>

              <div class="flex-container">
                <%= link_to 'Editar perfil', edit_person_registration_path(current_person), :class =>'navbar-link'%>
                
              </div>
                
              <div class="flex-container"> 
                <%= link_to "Salir", destroy_person_session_path, method: :delete, :class => 'navbar-link'%>
               
              </div>
          </div>    

            
   

<div class="footer">
Logged in as:
<strong><%= current_person.email %></strong><br>
</div>
                



        


  <%= yield %>


          
  </body>

</html>

app/views/layouts/member.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Insuvi</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

        <% if notice %><p class="alert alert-success"><%= notice %></p> <% end %>
      
        <% if alert %><p class="alert alert-danger"><%= alert %></p> <% end %>


        


  <%= yield %>
          
  </body>

</html>